#!/usr/bin/env python3
"""Curate + shrink a subset of the purchased PBR "Materials" pack
(src/assets/Materials/<Category>/<variant>/) into shop-ready floor/wall
products for the primitive3d room shell.

The raw pack ships 1024x1024 diffuse/normal/ao/height/metallic/smoothness/edge
maps per variant (several MB each, mostly uncompressed .bmp) across ~250
variants -- far too large to ship. This script picks a curated subset
(CURATED_MATERIALS below), resizes+recompresses just the diffuse map, and
writes a manifest the app can `require()` from directly.

Diffuse only, deliberately: normalMap was tried in sceneBuilder3D.ts and
produced fully black room-shell materials on-device (Android emulator,
expo-gl) -- BoxGeometry has no tangent attributes, and three.js's
derivative-based fallback tangent computation apparently degenerates to zero
normals in this GL context. Not worth shipping unused normal maps until
that's actually fixed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import NamedTuple

from PIL import Image

ROOT = Path(__file__).resolve().parents[4]
SOURCE_ROOT = ROOT / "src" / "assets" / "Materials"
PROCESSED_ROOT = ROOT / "src" / "assets" / "Materials" / "Processed"
MANIFEST_DIR = ROOT / "src" / "game" / "housing" / "assets" / "generated"
MANIFEST_PATH = MANIFEST_DIR / "materialCatalogManifest.ts"

DIFFUSE_SIZE = 512
THUMB_SIZE = 128
DIFFUSE_JPEG_QUALITY = 85
THUMB_JPEG_QUALITY = 80


class MaterialPick(NamedTuple):
    category: str
    variant: str
    kind: str  # 'floor' | 'wall'
    name: str
    cost: int


# Curated selection -- picked by eye from each variant's marketing-preview
# render (see the category folders under src/assets/Materials). Keep this
# list small; it's a first pass, more can be added the same way later.
CURATED_MATERIALS: list[MaterialPick] = [
    # Floors
    MaterialPick("Wood Planks", "1", "floor", "Rustic Plank Floor", 220),
    MaterialPick("Wood Planks", "5", "floor", "Weathered Plank Floor", 220),
    MaterialPick("Wood Planks", "8", "floor", "Knotted Plank Floor", 220),
    MaterialPick("Tiles", "2", "floor", "Floral Tile Floor", 220),
    MaterialPick("Tiles", "4", "floor", "Sunbaked Mosaic Floor", 220),
    MaterialPick("Tiles", "6", "floor", "Moroccan Tile Floor", 220),
    MaterialPick("Cobble Stone", "2", "floor", "River Cobble Floor", 220),
    MaterialPick("Cobble Stone", "5", "floor", "Mossy Cobble Floor", 220),
    MaterialPick("Grass", "3", "floor", "Meadow Grass Floor", 220),
    MaterialPick("Grass", "8", "floor", "Mossy Stone Grass Floor", 220),
    MaterialPick("Grass", "15", "floor", "Sunny Grass Floor", 220),
    # Walls
    MaterialPick("Indoor Walls", "2", "wall", "Cracked Plaster Wall", 240),
    MaterialPick("Indoor Walls", "4", "wall", "Sunbaked Plaster Wall", 240),
    MaterialPick("Stone Wall", "3", "wall", "Fieldstone Wall", 240),
    MaterialPick("Stone Wall", "8", "wall", "Slate Stone Wall", 240),
    MaterialPick("Damaged Wall", "1", "wall", "Weathered Stone Wall", 240),
    MaterialPick("Damaged Wall", "2", "wall", "Crumbling Stone Wall", 240),
    MaterialPick("Wall_with_plants", "3", "wall", "Ivy Stone Wall", 240),
    MaterialPick("Wall_with_plants", "6", "wall", "Overgrown Ivy Wall", 240),
]

MANIFEST_HEADER = """// AUTO-GENERATED by process_materials.py
// Do not edit manually.

export interface MaterialCatalogEntry {
  id: string;
  kind: 'floor' | 'wall';
  category: string;
  name: string;
  cost: number;
  diffuseRequirePath: any;
  thumbnailRequirePath: any;
}

export const materialCatalogManifest: MaterialCatalogEntry[] = [
"""


def slugify(text: str) -> str:
    import re

    text = text.replace("&", " and ")
    text = re.sub(r"[^0-9a-zA-Z]+", "", text)
    return text


def find_source_file(variant_dir: Path, stem_suffix: str) -> Path:
    matches = list(variant_dir.glob(f"*_{stem_suffix}.*"))
    if not matches:
        raise FileNotFoundError(f"No *_{stem_suffix}.* found in {variant_dir}")
    return matches[0]


def process_material(pick: MaterialPick) -> dict:
    variant_dir = SOURCE_ROOT / pick.category / pick.variant
    diffuse_src = find_source_file(variant_dir, "diffuseOriginal")

    material_id = f"Material_{slugify(pick.category)}_{pick.variant}"
    out_dir = PROCESSED_ROOT / slugify(pick.category) / pick.variant
    out_dir.mkdir(parents=True, exist_ok=True)

    diffuse_img = Image.open(diffuse_src).convert("RGB")
    diffuse_resized = diffuse_img.resize((DIFFUSE_SIZE, DIFFUSE_SIZE), Image.LANCZOS)
    diffuse_out = out_dir / "diffuse.jpg"
    diffuse_resized.save(diffuse_out, "JPEG", quality=DIFFUSE_JPEG_QUALITY)

    thumb = diffuse_img.resize((THUMB_SIZE, THUMB_SIZE), Image.LANCZOS)
    thumb_out = out_dir / "thumb.jpg"
    thumb.save(thumb_out, "JPEG", quality=THUMB_JPEG_QUALITY)

    def require_path(target: Path) -> str:
        rel = Path("../../../../assets/Materials/Processed") / target.relative_to(PROCESSED_ROOT)
        return str(rel).replace("\\", "/")

    print(f"Processed {pick.category}/{pick.variant} -> {out_dir.relative_to(ROOT)}")

    return {
        "id": material_id,
        "kind": pick.kind,
        "category": pick.category,
        "name": pick.name,
        "cost": pick.cost,
        "diffuseRequirePath": require_path(diffuse_out),
        "thumbnailRequirePath": require_path(thumb_out),
    }


def write_manifest(entries: list[dict]) -> None:
    MANIFEST_DIR.mkdir(parents=True, exist_ok=True)
    with MANIFEST_PATH.open("w", encoding="utf-8") as f:
        f.write(MANIFEST_HEADER)
        for entry in entries:
            f.write("  {\n")
            f.write(f"    id: '{entry['id']}',\n")
            f.write(f"    kind: '{entry['kind']}',\n")
            f.write(f"    category: {json.dumps(entry['category'])},\n")
            f.write(f"    name: {json.dumps(entry['name'])},\n")
            f.write(f"    cost: {entry['cost']},\n")
            f.write(f"    diffuseRequirePath: require('{entry['diffuseRequirePath']}'),\n")
            f.write(f"    thumbnailRequirePath: require('{entry['thumbnailRequirePath']}'),\n")
            f.write("  },\n")
        f.write("]\n")
    print(f"Wrote {len(entries)} entries to {MANIFEST_PATH.relative_to(ROOT)}")


def main() -> None:
    entries = [process_material(pick) for pick in CURATED_MATERIALS]
    write_manifest(entries)


if __name__ == "__main__":
    main()
