// Texture loading for the plain-quad room renderer. Loads individual
// floor/wall/furniture PNGs on demand (cached), keyed by the manifest ids
// generated by process_room_assets.py from assets/rooms/housingCore.json.
import * as THREE from 'three';
import { housingCoreAtlasManifest, RoomAtlasEntry } from './generated/housingCoreAtlasManifest';

export interface QuadTexture {
  texture: THREE.Texture;
  width: number;
  height: number;
  /** Measured skirt (px) from the asset-analysis pipeline -- how far the
   * decorative border extends below the tile's actual floor-contact line.
   * Falls back to 0 if the analyzer couldn't detect it. */
  skirt: number;
}

const manifestById = new Map<string, RoomAtlasEntry>(
  housingCoreAtlasManifest.map((entry) => [entry.id, entry])
);
const manifestByName = new Map<string, RoomAtlasEntry>(
  housingCoreAtlasManifest.map((entry) => [entry.name, entry])
);

const textureCache = new Map<string, Promise<THREE.Texture>>();

async function loadEntryTexture(entry: RoomAtlasEntry): Promise<THREE.Texture> {
  const { loadAsync } = require('expo-three');
  const texture: THREE.Texture = await loadAsync(entry.requirePath);
  (texture as any).colorSpace = (THREE as any).SRGBColorSpace ?? (THREE as any).sRGBEncoding;
  // NOTE: flipY is intentionally left at THREE's default (true). The legacy
  // Spine atlas pipeline forced this false for its own UV convention; plain
  // PlaneGeometry quads need the normal orientation, or asymmetric art (the
  // chair) renders upside down (symmetric tile patterns hid this before).
  texture.wrapS = THREE.ClampToEdgeWrapping;
  texture.wrapT = THREE.ClampToEdgeWrapping;
  texture.generateMipmaps = false;
  texture.minFilter = THREE.LinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.needsUpdate = true;
  return texture;
}

async function loadEntry(entry: RoomAtlasEntry): Promise<QuadTexture> {
  if (!textureCache.has(entry.id)) {
    textureCache.set(entry.id, loadEntryTexture(entry));
  }
  const texture = await textureCache.get(entry.id)!;
  return {
    texture,
    width: entry.metadata.trimmedRect.width,
    height: entry.metadata.trimmedRect.height,
    skirt: entry.metadata.skirt ?? 0,
  };
}

export async function loadFloorTexture(set: string, variant: string): Promise<QuadTexture | null> {
  const entry = manifestById.get(`${set}_${variant}`);
  if (!entry) {
    if (__DEV__) console.warn(`[housing] no floor texture for ${set}_${variant}`);
    return null;
  }
  return loadEntry(entry);
}

export async function loadWallTexture(set: string, variant: string): Promise<QuadTexture | null> {
  const entry = manifestById.get(`${set}_${variant}`);
  if (!entry) {
    if (__DEV__) console.warn(`[housing] no wall texture for ${set}_${variant}`);
    return null;
  }
  return loadEntry(entry);
}

// Furniture rest-pose art doesn't follow the set/variant naming scheme, so
// it's looked up by the exact source filename stem (e.g.
// "1x1_WoodChair_Front_Green") declared on the furniture variant.
export async function loadFurnitureTexture(assetName: string): Promise<QuadTexture | null> {
  const entry = manifestByName.get(assetName);
  if (!entry) {
    if (__DEV__) console.warn(`[housing] no furniture texture for ${assetName}`);
    return null;
  }
  return loadEntry(entry);
}
