#!/usr/bin/env python3
"""Regenerate cosmetic shop/equip thumbnail PNGs and their require() manifest.

Rerun this any time cosmetic products or colors change in
src/data/stores/cosmeticsStore.ts. It always regenerates every item and
overwrites the manifest wholesale -- no incremental/diffing complexity, since
capture is fast and the catalog is small.

Two-stage pipeline (see src/dev/CosmeticThumbnailCapture.tsx for stage 1):
  1. Triggers the app's dev-only thumbnail-capture screen via a deep link.
     It renders every cosmetic on the real Spine character (the same
     rendering path the game itself uses) and writes transparent PNGs to
     the app's private storage.
  2. This script waits for that to finish, pulls the PNGs down, and writes
     src/assets/cosmeticThumbnails/generated/cosmeticThumbnailManifest.ts --
     a flat `require()` table Metro can resolve statically (it can't resolve
     a fully dynamic `require(variable)`), mirroring the pattern already
     used for housing assets in
     src/game/housing/assets/process_room_assets.py -> generated/*.ts.

Requires: an Android emulator/device connected via adb, with the app already
running (any screen) and Metro serving it -- same dev workflow as manual
testing. Run directly:

    python src/data/cosmeticThumbnails/generate_thumbnails.py
"""

from __future__ import annotations

import os
import shutil
import subprocess
import time
from pathlib import Path

PACKAGE = "com.kevin.glidermon"
DEEP_LINK = "glidermon://dev/thumbnails"
DEVICE_OUTPUT_DIR = "files/cosmeticThumbnails"  # relative to the app's private data dir
TIMEOUT_SECONDS = 180
POLL_INTERVAL_SECONDS = 2
STABLE_POLLS_REQUIRED = 2  # consecutive unchanged counts before declaring done

ROOT = Path(__file__).resolve().parents[3]
MANIFEST_DIR = ROOT / "src" / "assets" / "cosmeticThumbnails" / "generated"

MANIFEST_HEADER = """// AUTO-GENERATED by src/data/cosmeticThumbnails/generate_thumbnails.py
// Do not edit manually -- rerun the script instead.
//
// Flat require() table keyed by cosmeticsStore catalog item id. Metro can't
// resolve a fully dynamic require(variable), so this manifest exists purely
// to give CosmeticThumbnail.tsx a static lookup table.

export const cosmeticThumbnailManifest: Record<string, any> = {
"""
MANIFEST_FOOTER = "};\n"


def resolve_adb() -> str:
    """Find adb, falling back to ANDROID_HOME/platform-tools like the
    project's documented manual workflow does for fresh shells."""
    found = shutil.which("adb")
    if found:
        return found
    android_home = os.environ.get("ANDROID_HOME") or os.environ.get("ANDROID_SDK_ROOT")
    if android_home:
        candidate = Path(android_home) / "platform-tools" / ("adb.exe" if os.name == "nt" else "adb")
        if candidate.exists():
            return str(candidate)
    raise SystemExit(
        "adb not found on PATH and ANDROID_HOME/platform-tools/adb doesn't exist. "
        "Set ANDROID_HOME or add platform-tools to PATH."
    )


def run(adb: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run([adb, *args], capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"adb {' '.join(args)} failed:\n{result.stderr}")
    return result


def ensure_device_connected(adb: str) -> None:
    result = run(adb, "devices")
    lines = [l for l in result.stdout.splitlines()[1:] if l.strip()]
    if not any(l.endswith("device") for l in lines):
        raise SystemExit("No adb device/emulator connected. Start one and try again.")


def restart_app_fresh(adb: str) -> None:
    # CosmeticThumbnailCapture only runs its capture loop once per mount
    # (a startedRef guard prevents re-running it) -- re-firing the same deep
    # link while the app is *already* sitting on that screen doesn't remount
    # the component, so no new capture happens and the screen just keeps
    # showing its previous run's stale "N/N captured" text. Confirmed
    # empirically: the on-screen text read "56/56" while the device output
    # directory was actually empty. A full force-stop + relaunch guarantees
    # a fresh mount every time, matching the manual testing workflow that
    # proved reliable while tuning this script.
    print("Restarting app for a fresh capture-screen mount...")
    run(adb, "shell", "am", "force-stop", PACKAGE)
    run(adb, "shell", "monkey", "-p", PACKAGE, "-c", "android.intent.category.LAUNCHER", "1")
    time.sleep(10)  # let Metro finish bundling on a cold start


def list_device_pngs(adb: str) -> list[str]:
    result = run(adb, "shell", f"run-as {PACKAGE} ls {DEVICE_OUTPUT_DIR}", check=False)
    if result.returncode != 0:
        return []  # directory doesn't exist yet
    return [l.strip() for l in result.stdout.splitlines() if l.strip().endswith(".png")]


def count_device_pngs(adb: str) -> int:
    return len(list_device_pngs(adb))


def clear_device_output(adb: str) -> None:
    # Without this, PNGs from items removed from the catalog since the last
    # run would linger forever and get pulled into the manifest.
    run(adb, "shell", f"run-as {PACKAGE} rm -rf {DEVICE_OUTPUT_DIR}", check=False)


def trigger_capture(adb: str) -> None:
    print(f"Triggering capture via {DEEP_LINK} ...")
    run(adb, "shell", "am", "start", "-a", "android.intent.action.VIEW", "-d", DEEP_LINK)


def wait_for_completion(adb: str) -> int:
    # console.log from this app doesn't reach Android's native logcat in this
    # project's setup (Metro captures it over its own bridge instead), so
    # completion can't be detected by watching logcat for the capture
    # screen's "done" log line -- confirmed empirically (the app's own log
    # showed completion while `adb logcat -d` had nothing). Polling the
    # output directory's file count until it stops growing is a more direct
    # signal anyway: it doesn't depend on log plumbing at all.
    print("Waiting for capture to finish (polling device output directory)...")
    deadline = time.time() + TIMEOUT_SECONDS
    last_count = -1
    stable_polls = 0
    while time.time() < deadline:
        count = count_device_pngs(adb)
        if count > 0 and count == last_count:
            stable_polls += 1
            if stable_polls >= STABLE_POLLS_REQUIRED:
                return count
        else:
            stable_polls = 0
        last_count = count
        time.sleep(POLL_INTERVAL_SECONDS)
    raise SystemExit(
        f"Timed out after {TIMEOUT_SECONDS}s waiting for capture to complete "
        f"(last seen: {last_count} PNGs). Is the app running and Metro connected?"
    )


def pull_thumbnails(adb: str) -> list[Path]:
    print("Pulling captured PNGs off device...")
    filenames = list_device_pngs(adb)
    if not filenames:
        return []

    if MANIFEST_DIR.exists():
        for existing in MANIFEST_DIR.glob("*.png"):
            existing.unlink()
    MANIFEST_DIR.mkdir(parents=True, exist_ok=True)

    # The app's private data dir isn't directly adb-pullable (permission
    # denied) on a normal debug build, and `run-as ... cp` to /sdcard also
    # fails under scoped storage on this Android version -- `exec-out
    # run-as ... cat <file>` streaming raw bytes to a local file, one file at
    # a time, is what actually worked reliably (confirmed manually pulling
    # individual thumbnails while tuning crop rects). Must run in *binary*
    # mode -- PNG bytes aren't valid UTF-8, and text-mode decoding corrupts
    # them.
    pngs: list[Path] = []
    for filename in filenames:
        dest = MANIFEST_DIR / filename
        result = subprocess.run(
            [adb, "exec-out", "run-as", PACKAGE, "cat", f"{DEVICE_OUTPUT_DIR}/{filename}"],
            capture_output=True,
        )
        if result.returncode != 0 or not result.stdout:
            print(f"  WARNING: failed to pull {filename}: {result.stderr!r}")
            continue
        dest.write_bytes(result.stdout)
        pngs.append(dest)

    return sorted(pngs)


def write_manifest(pngs: list[Path]) -> None:
    manifest_path = MANIFEST_DIR / "cosmeticThumbnailManifest.ts"
    with manifest_path.open("w", encoding="utf-8") as f:
        f.write(MANIFEST_HEADER)
        for png in pngs:
            item_id = png.stem
            f.write(f"  {item_id!r}: require('./{png.name}'),\n")
        f.write(MANIFEST_FOOTER)
    print(f"Wrote manifest: {manifest_path} ({len(pngs)} entries)")


def main() -> None:
    adb = resolve_adb()
    ensure_device_connected(adb)
    restart_app_fresh(adb)
    clear_device_output(adb)
    trigger_capture(adb)
    count = wait_for_completion(adb)
    print(f"Capture finished: {count} PNGs on device.")
    pngs = pull_thumbnails(adb)
    if not pngs:
        raise SystemExit("No PNGs pulled -- check that the capture step actually wrote files.")
    write_manifest(pngs)
    print(f"Done: {len(pngs)} thumbnails generated.")


if __name__ == "__main__":
    main()
